### PR TITLE
Note package name map best practice

### PR DESCRIPTION
**Pull request by guybedford**
I don't think the HTTP/2 push comment is correct here as this would result in every HTML page visit getting the pushed package name map, whereas ideally this should be cached between page visits, or between page sections for multi-page apps.

### CODE REVIEW

**Comment by domenic** [comment]
Apologies for letting this languish. I don't believe this advice is correct; in particular it implies a server round-trip for first-time visitors. Similar to the advice to inline critical CSS instead of putting it in external `<link>` elements, Chrome web performance folks believe that inlining your import map (or H/2 pushing it) makes more sense.

Hope that helps.

**Comment by guybedford** [comment]
@domenic I think it is situation dependent - if its an SPA, then sure inline the import map, but if you are server-rendering your app and have a very large import map (multiple KB), then caching could be a more important factor.

**Comment by domenic** [comment]
We've found that inlining critical resources is best practice regardless of application architecture; e.g. there are Lighthouse checks for doing so in the CSS case.

**Comment by guybedford** [comment]
> We've found that inlining critical resources is best practice regardless of application architecture

If first-load is the optimization goal, then agreed that would be the result.

**Pull request closed without merging**
